### ISSUE TITLE
Megadetector endpoint can return objects outside of images' dimensions

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ml#103]
e.g. this [image](https://doo86afh9dk8g.cloudfront.net/original/28524fa78e2cff851c534553b781728b-original.jpg) returns:

```
[
  {
    x1: -0.002311658812686801,
    y1: -0.021098900586366653,
    x2: 1.0007762908935547,
    y2: 1.0159189701080322,
    confidence: 0.3330053687095642,
    class: 2
  }
]
```

@rbavery thinks this should soon be addressed by the letterbox fix, but we should double check once that is live.

**Comment by rbavery** [comment]
I think this is addressed after we fixed the shifted bbox issue.
