### ISSUE TITLE
Get MIRA API working offline for local development

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ml#20]
Unfortunately, serverless-offline does not perform the base64 encoding step that API gateway does before passing the request body on to the Lambda handler (see [serverless-offline issue #464](https://github.com/dherault/serverless-offline/issues/464)). I'm not sure we can get a local development workflow working without it. 

In the mean time, you have to re-deploy the entire serverless app each time you make a change during development.

**Comment by cloudworkpro-dave** [comment]
@nathanielrindlaub Hi Nathan, any progress on this?

**Comment by nathanielrindlaub** [comment]
Closing this out as MIRAv2 won't need the API service.
